[package]
name = "coroutines"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
cc = "1.0.67"

[dependencies]
libc = "0.2.169"
nix = { version = "0.29.0", features = ["poll"] }
